### ISSUE TITLE
crypto error

### ISSUE THREAD

**Issue by hellt** [mysocketio/mysocketctl#21]
Hi @atoonk 

```bash
docker run --rm -it -- entrypoint bash python:3.8

pip3 install mysocketctl

<login>

Logged in! Token stored in /root/.mysocketio_token
```

```
root@5edbf2347af2:/# mysocketctl connect --port 3000 --name test
barf on {token}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mysocketctl/utils.py", line 61, in get_auth_header
    data = jwt.decode(token, verify=False)
  File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mysocketctl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mysocketctl/connect.py", line 137, in connect
    authorization_header = get_auth_header()
  File "/usr/local/lib/python3.8/site-packages/mysocketctl/utils.py", line 64, in get_auth_header
    data = jwt.decode(token, verify=False)
  File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

root@5edbf2347af2:/# python --version
Python 3.8.7
```

**Comment by atoonk** [comment]
Looks like PyJWT changed their API in the new 2.0 release, which came out 2 weeks ago or so.
I will pin the version number in my code going forward.

for now, you can do this to work around it.
```pip install PyJWT==1.7.1```

let me know how it goes.

**Comment by atoonk** [comment]
Fix pushed to pypi. If you try a fresh install, you should now get mysocketctl 0.14 (check with ```pip3 freeze```)

btw, if you run in docker, make sure the private key is available, otherwise you'll see something like this:
```
add566c8cb8d4ce5828ea8fe097411b9@ssh.mysocket.io: Permission denied (publickey).
Disconnected... Automatically reconnecting now..
```

**Comment by hellt** [comment]
thanks, solved
